spring:
  application:
    name: artisan-backend
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 127.0.0.1:9300

  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
  security:
    user:
      name: admin
      password: admin

initial-import:
  enabled: true